defaults:
  - _self_
  - dataset_info
  - target_layers

currentDir: ${hydra:runtime.cwd}


model: VGG11_Weights.IMAGENET1K_V1
seed: 42
checkpoint: checkpoints

dataset: 
  name: imagenet
  path: ./data
  resize: 224

saliency:
  method: rise

metrics:
  n_steps: 32
  del_obscure: blur
  ins_obscure: grey


train:
  batch_size: 1
  max_epochs: 20
  lr: 1e-6
  weight_decay: 5e-4
  accelerator: cpu
  devices: 1
  device: "cpu"
  save_path: ./models
  num_workers: 1
  patience: 4
  finetune: False

log:
  path: ./logs
  wandb: True

wandb:
  project: saliency-benchmark
  entity: marcoparola



