defaults:
  - _self_
  - dataset_info
  - target_layers

currentDir: ${hydra:runtime.cwd}

mainDir: C:\Users\matte\Github\saliency-benchmark

modelDet: GroundedSam2
modelSam: GroundingDino

datasetDet:
  name: pascal_voc

model: ResNet50_Weights.IMAGENET1K_V1
seed: 42
checkpoint: checkpoints\finetuned_VGG11_Weights.IMAGENET1K_V1oxford-iiit-pet\model-epoch=69-val_loss=3.09.ckpt\finetuned_ResNet50_Weights.IMAGENET1K_V1cifar10\model-epoch=12-val_loss=1.51.ckpt

dataset: 
  name: cifar10
  path: ./data
  resize: 224

visualize:
  save_images: false

saliency:
  method: gradcam

metrics:
  name: iou
  n_pixels: 500
  output_file: "finetuned_ResNet50_cifar10_gradcam.txt"

train:
  batch_size: 32
  max_epochs: 20
  lr: 1e-6
  weight_decay: 5e-4
  accelerator: gpu
  devices: 1
  device: "cuda"
  save_path: ./models_trained
  num_workers: 1
  patience: 4
  finetune: True

log:
  path: ./logs
  wandb: True

wandb:
  project: saliency-benchmark
  entity: l-cocchella1



