defaults:
  - _self_
  - dataset_info

currentDir: ${hydra:runtime.cwd}

method: sidu
model: ResNet18_Weights.IMAGENET1K_V1
seed: 42

dataset: 
  name: cifar10
  path: ./data
  resize: 64

train:
  batch_size: 16
  max_epochs: 3
  lr: 1e-5
  weight_decay: 5e-4
  accelerator: cpu
  devices: 1
  save_path: ./models
  num_workers: 1
  log_every_n_steps: 100
  patience: 5

log:
  path: ./logs
  wandb: True

wandb:
  project: saliency-benchmark
  entity: marcoparola

