defaults:
  - _self_
  - dataset_info
  - target_layers

currentDir: ${hydra:runtime.cwd}


model: ResNet18_Weights.IMAGENET1K_V1
seed: 42
checkpoint: null

dataset: 
  name: cifar10
  path: ./data
  resize: 256

saliency:
  method: sidu

metrics:
  n_steps: 128
  del_obscure: blur
  ins_obscure: grey

train:
  batch_size: 4
  max_epochs: 1
  lr: 5e-5
  weight_decay: 5e-4
  accelerator: gpu
  devices: 1
  device: "cuda"
  save_path: ./models
  num_workers: 1
  log_every_n_steps: 100
  patience: 5

log:
  path: ./logs
  wandb: True

wandb:
  project: saliency-benchmark
  entity: marcoparola



