defaults:
  - _self_
  - dataset_info
  - target_layers

currentDir: ${hydra:runtime.cwd}

mainDir: C:\Users\MyPC\Desktop\Tesi\saliency-benckhmark

model: ResNet18_Weights.IMAGENET1K_V1
seed: 42
checkpoint: checkpoints\finetuned_ResNet18_Weights.IMAGENET1K_V1cifar10\model-epoch=28-val_loss=1.52.ckpt

dataset: 
  name: cifar10
  path: ./data
  resize: 224

visualize:
  save_images: false

saliency:
  method: gradcam

metrics:
  n_pixels: 500

train:
  batch_size: 1
  max_epochs: 20
  lr: 1e-6
  weight_decay: 5e-4
  accelerator: cpu
  devices: 1
  device: "cpu"
  save_path: ./models
  num_workers: 1
  patience: 4
  finetune: True

log:
  path: ./logs
  wandb: True

wandb:
  project: saliency-benchmark
  entity: l-cocchella1



