defaults:
  - _self_
  - dataset_info
  - target_layers

currentDir: ${hydra:runtime.cwd}

mainDir: C:\Users\matte\Github\saliency-benchmark

modelDet: GroundedSam2
modelSam: Florence2

datasetDet:
  name: coco2017

model: VGG11_Weights.IMAGENET1K_V1
seed: 42
checkpoint: checkpoints\finetuned_VGG11_intel_image.ckpt

dataset: 
  name: intel_image
  path: ./data
  resize: 224

visualize:
  save_images: true

mask:
  dataset: True
  concepts: "Beak/Feathers/Eyes"
  file_image: "bird.jpg"

saliency:
  method: lime
  dataset: False
  file_image: "bird.jpg"

woe:
  dataset: True
  classes: ['English springer', 'cassette player', 'church', 'garbage truck', 'gas pump', 'parachute']
  concepts: ['Ears', 'Muzzle','Digital display','Facade','Bell Tower','Cab','Wheel','Tank','Canopy']
  concept_presence_method: iou
  concept_favor_against: False

metrics:
  name: iou
  n_pixels: 500

train:
  batch_size: 32
  max_epochs: 20
  lr: 1e-6
  weight_decay: 5e-4
  accelerator: gpu
  devices: 1
  device: "cuda"
  save_path: ./models_trained
  num_workers: 1
  patience: 4
  finetune: True

log:
  path: ./logs
  wandb: True

wandb:
  project: saliency-benchmark
  entity: m-razz



