# please note that the pretrained model name follows the capitalization of the model name available at https://pytorch.org/vision/stable/models.html#table-of-all-available-classification-weights
target_layers:
  ResNet18: model.layer4.1.conv2
  ResNet34: model.layer4.2.conv1
  ResNet50: model.layer4.2.conv3
  VGG11: model.0.features.20
  VGG13: model.features.24
  VGG16: model.features.30
  EfficientNet_B0: model.features.8


